### ISSUE TITLE
Pro builder android crash

### ISSUE THREAD

**Issue by Daniel95** [Daniel95/Hexagonia#1]
## Verwacht gedrag

Het project zou moeten gebuild kunnen worden voor android zonder errors of crashes.

## Huidig gedrag

Het project kan niet builden door errors door die te maken hebben met de geimporteerde pro builder asset.

## Stappen om te reproduceren

1. Ga naar de player_movement branch
2. Klik op File -> Build Settings -> Build

## Gedetailleerde beschrijving

Shaders setting instellen zodat ze compatible zijn met android.

**Comment by tommtom9** [comment]
Opgelost op "Probuilder" branch, commit: "ProBuilder fix for android"

## Oplossing
1. Find de "Checker.mat" material onder "Assets/ProCore/ProBuilder/Material/"
2. Verander "Standard(Roughness setup)" naar "Standard"
