### ISSUE TITLE
Camera Holder specifiek gemaakt voor de main scene

### ISSUE THREAD

**Issue by Daniel95** [Daniel95/Hexagonia#6]
## Verwacht gedrag

De CameraHolder zou een flexibel scripts moeten zijn dat gebruik kan worden om de camera tussen verschillende scene's te switchen.

## Huidig gedrag

De CameraHolder Script is specifiek gemaakt voor de main scene. Als je dit script in andere scenes gebruikt gaan er dingen mis, dit komt doordat er anderen scripts worden aangestuurd via de CameraHolder die alleen in de main scene 

## Gedetailleerde beschrijving

Door overerving te gebruiken kunnen we de basis functionaliteiten van de CameraHolder in een class stoppen, en deze uitbreiden met code specifiek voor een scene wanneer dit nodig. Door een nieuw scripts aan te maken en deze te laten overerven van de CameraHolder, kun je nieuwe functionaliteiten toevoegen zonder je de orginele scripts hoeft aan te passen.

**Comment by Dannyfaction** [comment]
Het refactoren van de CameraHolder heeft een bug veroorzaakt die de camera niet goed meer centreert nadat je van scene veranderd. Deze bug is nu gefixed en het systeem is nu af.
